#!/bin/bash -eu

if [ $USER == 'root' ]; then USER=$SUDO_USER; HOME="/home/${SUDO_USER}"; fi
SCRIPT=`readlink -f $0`; SCRIPTPATH=`dirname "$SCRIPT"`; cd "$SCRIPTPATH";
PROCESS_TYPE=; if [ "$#" -eq 0 ]; then PROCESS_TYPE="--build"; else PROCESS_TYPE=${1}; fi
case ${PROCESS_TYPE} in
  "--deploy") ;&
  "--purge") ;&
  "--build")
    if [ "$0" != "tools/package" && "$0" != "./tools/package" ]; then
      echo "Must be run from parent project containing directory NOT $0";
      exit 1;
    fi
    if [[ $EUID -ne 0 ]]; then
      echo "This script must be run as root" 1>&2;
      exit 1;
    fi
    read -p "Save package as location/name_version-release_architecture.deb [../apache2-webshop-conf_0.1-0_all.deb]: " SAVE_AS;
    SAVE_AS=${SAVE_AS:-"../apache2-webshop-conf_0.1-0_all.deb"};
  case ${PROCESS_TYPE} in
    "--deploy") ;&
    "--purge") ;&
    "--build")
      echo "BUILDING...";
      if [ -f ${SAVE_AS} ]; then rm -f ${SAVE_AS}; fi
      if [ ! $(getent group developer) ]; then sudo addgroup developer; fi
      sudo chown -R root:root ../debian/etc;
      sudo chown -R root:root ../debian/usr;
      sudo chown -R root:www-data ../debian/var/www/;
      sudo dpkg-deb --build ../debian;
      echo "renaming '../debian.deb' to '${SAVE_AS}'"
      mv ../debian.deb ${SAVE_AS};
      sudo chmod 775 ${SAVE_AS};
      sudo chown ${USER}:developer ${SAVE_AS}
      sudo chown -R ${USER}:${USER} ../debian;
      echo "BUILD SUCCESFULLY COMPLETED!";
      ;;
  esac
  case ${PROCESS_TYPE} in
    "--deploy") ;&
    "--purge")
      echo "PURGING...";
      sudo apt remove apache2-webshop-conf -y;
      sudo apt purge mysql-server php php-mysql php-xdebug apache2 -y;
      sudo apt autoremove -y;
      if [ -d /var/www/ ]; then
        echo " Removing /var/www";
        sudo rm -Rf /var/www;
      fi
      sudo apt --fix-broken remove -y;
      echo "PURGE SUCCESFULLY COMPLETED!";
      ;;
  esac
  case ${PROCESS_TYPE} in
    "--deploy")
      echo "DEPLOYING Apache2 WebShop Configuration (LAMP)...";
      sudo apt update;
      sudo apt install openssl postfix apache2 -y;
      sudo ufw allow OpenSSH;
      sudo ufw allow "Apache Full";
      sudo ufw enable;
      sudo apt install mysql-server -y;
      sudo apt-get install php libapache2-mod-php php-mcrypt php-mysql php-xdebug -y;
      echo "INSTALLING APACHE2 WEBSHOP CONFIGURATION PACKAGE";
      sudo dpkg -i ${SAVE_AS};
      echo "REINSTALL WITH DEPENDANCIES";
      if [ -d /etc/apache2/ssl ]; then
        sudo rm -rf /etc/apache2/ssl;
      fi
      sudo mkdir /etc/apache2/ssl;
      echo "CREATING SELF-SIGNED SSL CERTIFICATE; USE ${HOSTNAME}.lan as FDQN";
      sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/apache2/ssl/apache.key -out /etc/apache2/ssl/apache.crt;
      sudo chown root:ssl-cert /etc/apache2/ssl/*;
      sudo chmod 710 /etc/apache2/ssl/*;
      sudo systemctl start apache2.service;
      sudo systemctl start mysql.service;
      sudo systemctl start postfix.service;
      echo "DEPLOY SUCCESFULLY COMPLETED!";
      ;;
  esac
  ;;
  *)
    echo "USAGE: ...";
    exit 1
    ;;
esac
