#!/bin/bash -eu

if [ $USER == 'root' ]; then USER=$SUDO_USER; HOME="/home/${SUDO_USER}"; fi
SCRIPT=`readlink -f $0`; SCRIPTPATH=`dirname "$SCRIPT"`; cd "$SCRIPTPATH";
PROCESS_TYPE=; if [ "$#" -eq 0 ]; then PROCESS_TYPE="--build"; else PROCESS_TYPE=${1}; fi
case ${PROCESS_TYPE} in
  "--deploy") ;&
  "--purge") ;&
  "--build")
    if [ "$0" != "tools/package" ]; then
      echo "Must be run from parent project containing directory NOT $0";
      exit 1;
    fi
    if [[ $EUID -ne 0 ]]; then
      echo "This script must be run as root" 1>&2;
      exit 1;
    fi
    read -p "Save package as location/name_version-release_architecture.deb [../apache2-webshop-conf_0.1-0_all.deb]: " SAVE_AS;
    SAVE_AS=${SAVE_AS:-"../apache2-webshop-conf_0.1-0_all.deb"};
  case ${PROCESS_TYPE} in
    "--deploy") ;&
    "--purge") ;&
    "--build")
      echo "BUILDING...";
      if [ -f ${SAVE_AS} ]; then rm -f ${SAVE_AS}; fi
      if [ ! $(getent group developer) ]; then sudo addgroup developer; fi
      sudo chown -R root:root ../debian/etc;
      sudo chown -R root:root ../debian/usr;
      sudo chown -R root:www-data ../debian/var/www/;
      sudo dpkg-deb --build ../debian;
      echo "renaming '../debian.deb' to '${SAVE_AS}'"
      mv ../debian.deb ${SAVE_AS};
      sudo chmod 775 ${SAVE_AS};
      sudo chown ${USER}:developer ${SAVE_AS}
      sudo chown -R ${USER}:${USER} ../debian;
      echo "BUILD SUCCESFULLY COMPLETED!";
      ;;
  esac
  case ${PROCESS_TYPE} in
    "--deploy") ;&
    "--purge")
      echo "PURGING...";
      sudo apt remove -y apache2-webshop-conf;
      sudo apt purge -y apache2;
      sudo apt autoremove -y;
      if [ -d /etc/apache2/ ]; then
        echo " Removing /etc/apache2";
        sudo rm -Rf /etc/apache2;
      fi
      if [ -d /var/www/ ]; then
        echo " Removing /var/www";
        sudo rm -Rf /var/www;
      fi
      echo "PURGE SUCCESFULLY COMPLETED!";
      ;;
  esac
  case ${PROCESS_TYPE} 
    "--deploy")
      echo "DEPLOYING..."
      sudo dpkg -i ${SAVE_AS};
        echo "REINSTALL WITH DEPENDANCIES";
        sudo apt --fix-broken install -y;
      echo "DEPLOY SUCCESFULLY COMPLETED!";
      ;;
  esac
  ;;
  *)
    echo "USAGE: ...";
    exit 1
    ;;
esac
